### ISSUE TITLE
Void infestor ability bug

### ISSUE THREAD

**Issue by MagentaLizard** [yekoc/Risk-Of-Rain-2-Mods#8] opened 2023-08-03 17:00 UTC
When i'm at full corruption and about to spawn the infestors there's a chance the game will freeze and crash

Mod list: 0189bc55-5586-ad76-3da4-3462cc9bebb3

**Comment by yekoc** [comment] 2023-08-04 11:36
It's usually helpful with crash reports to provide a copy of the game's engine (not bepinex) log.
It can be found under `C:\Users\<UserName>\AppData\LocalLow\Hopoo Games, LLC\Risk of Rain 2\` ,named `Player.log`

**Comment by MagentaLizard** [comment] 2023-08-04 12:39
[Player.log](https://github.com/yekoc/Risk-Of-Rain-2-Mods/files/12260806/Player.log)

**Comment by yekoc** [comment] 2023-08-04 17:57
Yes but that log doesn't have anything that indicates a crash.

**Comment by MagentaLizard** [comment] 2023-11-24 20:18
[Player.log](https://github.com/yekoc/Risk-Of-Rain-2-Mods/files/13462000/Player.log)

Hasn't crashed again but everything still goes white. It also seems to teleport me far off the map and i can still see things like the tp symbol from far away.

Also some voidtouched allies randomly try to kill each other, my drones, or even me despite doing no damage.

**Comment by MagentaLizard** [comment] 2023-11-24 20:18
Also sorry it took so long to get back to this. Not been feeling so good for a while.

**Comment by yekoc** [comment] 2023-11-24 22:38
the only relevant thing in the log is that the game can't find anywhere to put the infestors because it's target (you) is at (1595726000000000000000000000000000.0, 35.0, -106.7),which means that you got teleported there before the infestation actually triggered.The logs indicates that the white screen is because your camera can't handle being at this position.
There isn't really anything on this end that can teleport you away like that,so I can only chalk it up to some weird interaction with another mod,do you have anything else installed that deals with infestors or the void fiend?

The AI attacking allies is a vanilla bug/feature,there are a few mods that fix it as far as I am aware,though I don't know if any do _just_ that,instead of being a collection of tweaks.

**Comment by yekoc** [comment] 2023-11-24 23:02
I have been told by the mods author that this caused by the mod Optimization (HIFU-Optimization) and that he himself has been trying to track down the bug but is having issues because it seems to be hardware specific,I have passed along the log you sent and will ping you here if I learn of a fix.
Thanks again for the report and the subsequent help with the logs,I'll be closing the issue but feel free to post further comments if you yourself come across more info that might be relevant.

**Closed by yekoc** 2023-11-24 23:02 UTC

**Comment by MagentaLizard** [comment] 2023-11-24 23:04
Aight thank you man
